apiVersion: v1
kind: Pod
metadata:
  name: carnac-example
  namespace: carnac
  labels:
    app: app
spec:
  containers:
  - name: carnac-container
    image: docker.io/carllafong/carnac:latest
    ports:
    - containerPort: 8080
